name:                owenbot
version:             0.1.0.0
github:              "yellowtides/owenbot-hs"
author:              "Infowmatics Devs"
copyright:           "2022 Infowmatics Devs"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A neat Discord bot written in Haskell.

dependencies:
- aeson == 1.5.6.0 # comes with discord-haskell
- base >= 4.7 && < 5
- base64 # for decoding base64 audio in ipa tts
- bytestring # comes with discord-haskell
- containers # comes with discord-haskell
- discord-haskell == 1.13.0
- discord-haskell-monad == 1.2.0
- directory
- html-entities
- http-conduit
- http-types # comes with http-conduit
- mtl # comes with discord-haskell
- network-bsd
- parsec
- pointfree == 1.1.1.8
- process
- random
- req # comes with discord-haskell
- regex-tdfa
- safe-exceptions # comes with discord-haskell
- split
- time # comes with discord-haskell
- text
- unliftio == 0.2.20.1 # comes with discord-haskell
- unordered-containers # comes with discord-haskell
- vector # comes with discord-haskell

library:
  source-dirs:
    - src
    - src/listeners

executables:
  owenbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - owenbot

tests:
  owenbot-test:
    main:                Spec.hs
    source-dirs:
      - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wno-missing-fields
    dependencies:
    - owenbot
    - QuickCheck
    - quickcheck-instances # required for arbitrary Text
    - hspec
    - HMock

